version: '3'
services:
  mysql:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docs/tables.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3316:3306"
  nuxt:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/chatgpt_clone
    ports:
      - "3010:3000"
    depends_on:
      - mysql
