CREATE DATABASE IF NOT EXISTS `chatgpt_clone` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `chatgpt_clone`;

-- 用户表
CREATE TABLE IF NOT EXISTS `m_user` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(64) NOT NULL,
    `password` VARCHAR(64) NOT NULL,
    `nickname` VARCHAR(64) DEFAULT NULL,
    `email` VARCHAR(255) DEFAULT NULL,
    `phone` VARCHAR(64) DEFAULT NULL,
    `gender` TINYINT DEFAULT 0,
    `role` VARCHAR(100) DEFAULT 'admin',
    `is_deleted` TINYINT DEFAULT 0,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `username` (`username`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- 对话表
CREATE TABLE IF NOT EXISTS `m_dialog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` INTEGER NOT NULL,
    `name` VARCHAR(64) DEFAULT NULL,
    `is_deleted` TINYINT DEFAULT 0,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `user_id` (`user_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- 消息表
CREATE TABLE IF NOT EXISTS `m_message` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `dialog_id` INTEGER NOT NULL,
    `user_id` INTEGER NOT NULL,
    `answer_id` INTEGER DEFAULT NULL,
    `question` VARCHAR(2046) DEFAULT NULL,
    `answer` VARCHAR(2046) DEFAULT NULL,
    `is_deleted` TINYINT DEFAULT 0,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `dialog_id` (`dialog_id`),
    KEY `user_id` (`user_id`),
    KEY `answer_id` (`answer_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- 答案表
CREATE TABLE IF NOT EXISTS `m_answer` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `field` VARCHAR(64) DEFAULT NULL,
    `keyword` VARCHAR(255) NOT NULL,
    `answer` VARCHAR(2046) NOT NULL,
    `is_deleted` TINYINT DEFAULT 0,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT INTO `chatgpt_clone`.`m_user` (`id`, `username`, `password`, `nickname`, `email`, `phone`, `gender`, `role`, `is_deleted`, `created_at`, `updated_at`) VALUES (1, 'Jason Kennedy', 'Kw2agcG7rJ', 'Jason Kennedy', 'kennedy92@icloud.com', '614-368-2406', 28, 'admin', 0, '2002-02-01 09:56:04', '2006-09-01 22:37:55');

INSERT INTO `chatgpt_clone`.`m_dialog` (`id`, `user_id`, `name`, `is_deleted`, `created_at`, `updated_at`) VALUES (1, 1, NULL, 0, '2023-07-28 13:27:53', '2023-07-28 13:27:53');

INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (1, 'Education', 'China\'s education system ', 'China\'s education system is managed at both the national and local levels. The Ministry of Education is the main formulating and managing agency for China\'s national education policy and is responsible for directing and supervising education nationwide. At the same time, local governments are responsible for the specific management and implementation of education within their respective jurisdictions.', 0, '2023-07-29 00:29:16', '2023-07-29 00:29:16');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (2, 'Education', 'compulsory education', 'Compulsory education is the basic education stage in the Chinese education system, usually including primary and junior high schools. Compulsory education was free and universal, and every child was entitled to nine years of compulsory education. In recent years, China has also promoted the extension of nine-year compulsory education, striving to allow more students to receive high-quality education.', 0, '2023-07-29 00:29:16', '2023-07-29 00:29:16');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (3, 'Education', 'China\'s higher education system organized', 'China\'s higher education system consists of universities and colleges. A university in China usually refers to a comprehensive institution of higher learning that offers undergraduate and postgraduate programs. College refers to a vocational higher education institution, mainly cultivating application-oriented talents. There are two types of universities and colleges in China, public and private, but public schools still dominate.', 0, '2023-07-29 00:29:16', '2023-07-29 00:29:16');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (4, 'Education', 'China\'s school system/public or private', 'China\'s school system is dominated by public schools, especially at the compulsory and higher education levels. Public schools are funded and managed by the Government, provide the main channels for basic and higher education, and account for most of the student population. Public schools typically aim to provide inclusive education, characterized by lower tuition fees and higher educational resources.However, private schools are also increasing and growing in China. Private schools are schools founded and operated by private institutions or individuals that offer similar educational content and curriculum to public schools but charge higher tuition fees. Private schools are particularly prominent in the field of higher education, offering more specialized and career-oriented educational options.It should be noted that whether it is a public school or a private school, in China\'s education system, it is necessary to comply with the provisions of national education regulations and policies to ensure the quality and equity of education. Both public and private schools are subject to supervision and evaluation by the education authorities.', 0, '2023-07-29 00:29:16', '2023-07-29 00:29:16');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (5, 'Education', 'university entrance exam', 'China\'s university entrance exam, known as the gaokao (Higher Education Entrance Examination), is the main way for Chinese students to enter university. The gaokao is a national examination that is usually held in June every year. Students are required to take subject tests in the college entrance examination, including Chinese, mathematics, foreign language, and other subjects related to the chosen major. College entrance examination scores are crucial to a student\'s college admission, and admission results are often matched based on the student\'s test scores and voluntary choices.', 0, '2023-07-29 00:29:16', '2023-07-29 00:29:16');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (6, 'Education', 'characteristics and challenges', 'China\'s education system focuses on academic merit and exams when selecting students. Gaokao scores play a decisive role in university admission. However, in recent years, China\'s educational reform has gradually emphasized the cultivation of students\' creativity, practical ability, and comprehensive quality. In some schools and educational practices, characteristic courses and activities are introduced designed to stimulate students\' creativity and practical abilities.', 0, '2023-07-29 00:29:16', '2023-07-29 00:29:16');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (7, 'Education', 'academic achievement', 'China\'s education system has long focused on academic merit, with test scores in the selection and evaluation of students. This is mainly reflected in the college entrance examination (higher education entrance examination) as the main way for students to enter university, as well as some evaluation indicators and ranking systems in the education system. However, in recent years, China has also begun to realize the importance of cultivating students\' creativity and practical ability, and the goal of education reform has gradually shifted to comprehensive quality education. In some schools and educational practices, characteristic courses and activities are introduced designed to stimulate students\' creativity and practical abilities.', 0, '2023-07-29 00:29:16', '2023-07-29 00:29:16');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (8, 'Education', 'stressful/China\'s education system', 'In China\'s education system, student stress is generally greater. Students need to deal with many subject content and test-taking requirements and invest a lot of time and energy in preparing for and preparing for exams. This test-taking education leads to higher academic and competitive pressures for students. Parents have high expectations for their children\'s academic performance and can also increase student stress.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (9, 'Education', 'differences or values', 'There are some cultural differences or values in Chinese education. For example, the emphasis on education and the value of respecting teachers and teaching in traditional Chinese culture influence educational practice. At the same time, Chinese education emphasizes collectivism and social responsibility, encouraging students to contribute to society. Families and society also attach greater importance to education.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (10, 'Education', 'goals of China\'s education reform', 'The goals of China\'s education reform mainly include improving the quality and equity of education and promoting educational modernization and the cultivation of innovation capabilities. The objectives of educational reform also include reducing students\' academic burden, promoting their all-round development, and cultivating their creativity, practical ability, and comprehensive quality. The reform also involves curriculum reform, teacher training, education management and education investment, and strives to promote China\'s education to a higher level.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (11, 'Education', 'China\'s school system', 'China\'s school system is based on school segments, mainly including three stages: primary school, middle school, and university. ', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (12, 'Education', 'Primary School', 'Primary schools are usually 6 years long and are open to students between the ages of 6 and 12. The main objective is to provide basic education and cultivate students\' basic learning abilities and qualities. The curriculum at the primary school level mainly includes basic subjects such as Chinese, mathematics, English, science, and physical education.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (13, 'Education', 'Secondary School', 'Middle school is divided into two stages: junior high school and high school.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (14, 'Education', 'Junior High School', 'Junior High School is a three-year program for students between the ages of 12 and 15. In junior high school, students continue to study basic subjects such as Chinese, mathematics, English, and science, while adding other subjects such as history, geography, music, art, etc.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (15, 'Education', 'Senior High School', 'High school is a 3-year program for students between the ages of 15 and 18. Education at the high school level is divided into two main streams: liberal arts and science. Students choose the corresponding flow direction according to their own interests and abilities and choose subjects and study according to the requirements of the college entrance examination.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (16, 'Education', 'University', 'Undergraduate and graduate education is offered at the university level. Universities are usually 4 years long, and some majors maybe 5 years. Students can choose from different disciplines for in-depth study and research. The university curriculum is relatively flexible, with both professional courses and general education courses to cultivate students\' comprehensive quality and professional ability.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (17, 'Education', 'centralized or local', 'China\'s education system is jointly managed by the central and local governments. The central government, through the Ministry of Education, formulates educational policies and standards and supervises and directs education throughout the country. At the same time, local governments are responsible for the specific management and implementation of education within their respective jurisdictions, including the operation of schools and curricula. This management model is designed to ensure the implementation of education policies, considering the need for centralization and local flexibility.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (18, 'Education', 'Planning and guidance by the central government', 'Planning and guidance by the central government: The Ministry of Education formulates the overall framework and direction of education policy in accordance with the national education development strategy. This includes educational reform, curriculum design, teacher training, and allocation of educational resources.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (19, 'Education', 'Planning and implementation of local governments', 'Planning and implementation of local governments: Local education departments formulate specific education plans and policies in accordance with the guidance of central policies and the actual local conditions. Local governments are responsible for promoting the implementation of education policies, including allocation, resource allocation, and teacher management.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (20, 'Education', 'School implementation and implementation', 'Under the guidance of educational policies, schools formulate and implement specific educational programs and curriculum settings according to the characteristics and positioning of the school itself. The school is responsible for the specific implementation of education and teaching, including enrollment and admission, teaching management, examination evaluation, etc.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (21, 'Education', 'Duration', 'Primary school is usually 6 years, secondary school is divided into junior high school and high school, and each stage is generally 3 years. Universities generally have a four-year undergraduate education.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (22, 'Education', 'Curriculum', 'Primary school focuses on the learning of basic subjects, such as Chinese, mathematics, English, science, etc. In junior high school, other subjects such as history, geography, music, and fine arts are added to the basic subjects. In high school, students choose different liberal arts or science learning directions according to their interests and abilities and strengthen the in-depth study of related subjects. At the university level, professional courses and general education courses are offered, and students can choose their own interests for in-depth study.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (23, 'Education', 'Teaching Methods', 'Teaching methods will be adjusted as more sections are added. The primary school level focuses on the teaching and learning of basic knowledge, and the teaching methods are relatively simple and straightforward. At the secondary and university levels, students focus on cultivating their analytical thinking ability and innovative ability, and teaching methods pay more attention to students\' active participation and independent thinking.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (24, 'Education', 'strict examination system', 'China\'s education system has a strict examination system, and examinations play an important role in student selection and evaluation. One of the most important exams is the gaokao (Higher Education Entrance Examination), which determines whether and which university a student will be able to enter a university. The gaokao is a national unified examination that involves Chinese, mathematics, foreign languages, and other subjects. Exam scores have an important impact on students\' future development and are one of the main ways for students to enter China\'s higher education system.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (25, 'Education', 'Higher Education Entrance Examination', 'Due to the fierce competition and importance of the gaokao, students usually put in a lot of effort to get good grades, including attending additional training classes and preparing for the exam. Gaokao scores are widely recognized as one of the important factors for students to enter their ideal universities and gain better career development opportunities. Therefore, the importance of the gaokao for students is quite high in the Chinese education system. However, in recent years, educational reform has gradually emphasized the cultivation of comprehensive quality education and comprehensive ability, trying to reduce the pressure of students\' examinations, and paying more attention to students\' creativity and practical ability.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (26, 'Education', 'competitive pressures', 'Gaokao competitive pressure: Gaokao is an important barrier for Chinese students to enter university, and test results have an important impact on students\' future development. Therefore, students usually invest a lot of time and energy in preparing and studying to achieve good results in the college entrance examination.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (27, 'Education', 'Study of many subjects', 'Study of many subjects: China\'s education system focuses on a wide range of subjects, and students are required to study multiple subjects, including Chinese, mathematics, English, science, social sciences, etc. This requires students to acquire a great deal of knowledge in a limited amount of time.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (28, 'Education', 'Examination system and evaluation system', 'Examination system and evaluation system: China\'s education system has a strict examination system, and students are required to take various exams, including midterm exams, final exams, mock exams, etc. A student\'s academic performance is important for its evaluation and promotion.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (29, 'Education', 'training and recruitment conditions', 'Educational background and professional knowledge: Teachers usually need to have relevant educational background and professional knowledge, such as pedagogy, psychology, etc.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (30, 'Education', 'Graduation from teacher training colleges', 'Graduation from teacher training colleges: Most primary and secondary school teachers need to receive special education and training in teacher training colleges and obtain corresponding teacher qualification certificates.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (31, 'Education', 'Selection exams and interviews', 'Selection exams and interviews: Teacher recruitment often includes a written test and an interview session to assess their expertise, teaching ability, and adaptability.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (32, 'Education', 'assessed and motivated', 'Teachers may be evaluated and motivated differently in different districts and schools. Generally, teachers\' evaluations consider aspects such as their teaching performance, student performance, quality of instruction, and feedback. Incentives may include salary, titles, promotions, awards, honors, etc.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (33, 'Education', 'STEM (science, technology, engineering, and mathematics) education?', 'China\'s education system places emphasis on STEM (science, technology, engineering, and mathematics) education. With the rapid development of technology and the changing needs of society, STEM education is very important for cultivating students\' creativity, problem-solving skills, and innovative spirit. The Chinese government and school system actively promote the development of STEM education and include it in the important agenda of education reform.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (34, 'Education', 'nurture creativity and innovation', 'Diversified teaching methods: The school adopts a variety of teaching methods, such as inquiry-based learning, project-based learning, and cooperative learning, to encourage students\' active participation, exploration, and practice, and cultivate their creative thinking and problem-solving skills.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (35, 'Education', 'Science and technology education', 'The school invests in the construction of science and technology laboratories and maker spaces, provides advanced scientific equipment and technical tools, and allows students to master scientific principles through practice and experimentation, and carry out innovative practical activities.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (36, 'Education', 'Competitions and competitions', 'The school organizes various science and technology competitions and innovation competitions to encourage students to participate in and showcase their creativity and innovative achievements. These competitions and competitions provide a platform for students to showcase their talents and innovative abilities.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (37, 'Education', 'Innovative education courses', 'The school offers innovative education courses, including science experiment courses, engineering design courses, programming courses, etc., to cultivate students\' creative thinking, problem-solving ability, and innovation ability.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (38, 'Education', 'Entrepreneurship education', 'Some schools offer entrepreneurship education programs that encourage students to cultivate innovative spirit and creativity through entrepreneurial practice and provide opportunities and support for innovation and entrepreneurship.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (39, 'Education', 'students\' interest', 'These methods are designed to stimulate students\' interest, develop problem-solving skills, encourage innovative thinking, and provide students with opportunities for practice and practice to develop their creativity and innovative abilities.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (40, 'Education', 'education system and university rankings', 'China\'s higher education system includes multiple levels of universities, colleges, and junior colleges. China\'s higher education system is large and home to many well-known universities and research institutes. Some Chinese universities have an international reputation and have achieved high positions in some university rankings. Among them, some well-known Chinese universities include Tsinghua University, Peking University, Fudan University, Shanghai Jiao Tong University, etc. University rankings are usually evaluated based on several factors, including teaching quality, research output, academic reputation, etc.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (41, 'Education', 'the proportion of international students in Chinese universities?', 'China has attracted more and more international students to study in China. Chinese universities offer a range of international student admissions programs and scholarship programs to provide international students with opportunities to study and research. Higher education institutions in China are also improving their support and services for international students.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (42, 'Education', 'educational technologies', 'China has made some progress in promoting the application of educational technology. Especially in recent years, due to the impact of the new crown epidemic, online learning and distance education have received more attention and applications. Many schools and educational institutions offer online courses and distance education programs that utilize the Internet and advanced educational technology to provide flexible learning methods.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (43, 'Education', 'online learning and distance education', 'China has made some progress in promoting the application of educational technology. Especially in recent years, due to the impact of the new crown epidemic, online learning and distance education have received more attention and applications. Many schools and educational institutions offer online courses and distance education programs that utilize the Internet and advanced educational technology to provide flexible learning methods.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (44, 'Education', 'educational inequality', 'Inequality in education is a problem facing China. Due to economic, geographical, and social differences, there are certain differences in the education gap between urban and rural areas in China. Some rural areas have relatively few educational resources and relatively insufficient teachers and educational facilities, which has led to the inequality of education between urban and rural areas. The government and society are working hard to narrow the gap between urban and rural education and invest more resources to improve educational conditions in rural areas.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (45, 'Education', 'urban and rural education?', 'Inequality in education is a problem facing China. Due to economic, geographical, and social differences, there are certain differences in the education gap between urban and rural areas in China. Some rural areas have relatively few educational resources and relatively insufficient teachers and educational facilities, which has led to the inequality of education between urban and rural areas. The government and society are working hard to narrow the gap between urban and rural education and invest more resources to improve educational conditions in rural areas.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (46, 'Education', 'special challenges', 'China faces special challenges such as an aging population and a declining birth rate, which also poses some new needs and challenges to the education system. An aging population means an increased demand for lifelong and continuing education, and education systems need to adapt to the needs of people of different ages. At the same time, the declining birthrate also poses challenges to school enrollment and the allocation of educational resources, and sustainable development methods need to be sought.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (47, 'Education', 'cultural inheritance', 'China\'s education system consciously promotes cultural inheritance and language education. Chinese education emphasizes cultivating students\' understanding and inheritance of Chinese culture. In primary and secondary education, students learn Chinese history, literature, language, and traditional culture to strengthen their understanding of Chinese culture. In addition, the Chinese education system also encourages students to learn Chinese (Mandarin) as a common language throughout the country to promote language exchange and cultural dissemination.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (48, 'Education', 'language education', 'China\'s education system consciously promotes cultural inheritance and language education. Chinese education emphasizes cultivating students\' understanding and inheritance of Chinese culture. In primary and secondary education, students learn Chinese history, literature, language, and traditional culture to strengthen their understanding of Chinese culture. In addition, the Chinese education system also encourages students to learn Chinese (Mandarin) as a common language throughout the country to promote language exchange and cultural dissemination.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (49, 'Education', 'employment challenges', 'In China, the employment situation of college students after graduation is relatively complicated. Due to the huge scale of higher education in China and the fierce competition in the job market, graduates face certain employment difficulties. Graduates in some professional fields may face employment challenges, while some popular majors have better job prospects. The government and school systems strive to provide career guidance and vocational training to help graduates better fit in the job market.', 0, '2023-07-29 00:29:29', '2023-07-29 00:29:29');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (50, 'Education', 'Sino-foreign cooperatively run school', 'Sino-foreign cooperatively run schools are relatively common in China. Higher education institutions in China cooperate with universities and educational institutions abroad to jointly develop programs and courses. These collaborative programs often provide international educational content and academic resources, providing international students with opportunities for study and research. The international student\'s study experience in China varies from individual to individual, but overall, higher education institutions in China provide a good learning environment and support services for international students.', 0, '2023-07-29 00:29:41', '2023-07-29 00:29:41');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (51, 'Education', 'international student', 'Sino-foreign cooperatively run schools are relatively common in China. Higher education institutions in China cooperate with universities and educational institutions abroad to jointly develop programs and courses. These collaborative programs often provide international educational content and academic resources, providing international students with opportunities for study and research. The international student\'s study experience in China varies from individual to individual, but overall, higher education institutions in China provide a good learning environment and support services for international students.', 0, '2023-07-29 00:29:41', '2023-07-29 00:29:41');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (52, 'Education', 'centralized or self-governing', 'China\'s education system is centralized. Education policies are formulated and guided by the central government, and local governments at all levels are responsible for specific education management and operation during the implementation process. The central government\'s education policy framework and guiding principles play an important role in the development of education nationwide, while local governments are responsible for specific policy implementation and education management. This centralized education system helps to ensure the uniformity and stability of education policies and gives local governments a certain degree of autonomy to adapt to the actual situation of each region.', 0, '2023-07-29 00:29:41', '2023-07-29 00:29:41');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (53, 'Education', 'curriculum uniform or selective', 'In China, the curriculum of students is unified to a certain extent, but there is also a certain degree of selectivity. The National Department of Education has developed a set of basic curriculum standards, including major subjects such as Chinese, mathematics, English, physics, chemistry, biology, history, geography, etc. These subjects are often core subjects that students must study. In addition, the school can set and adjust the curriculum according to the actual situation of the place and the school and provide some elective courses and professional direction choices.', 0, '2023-07-29 00:29:41', '2023-07-29 00:29:41');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (54, 'Education', 'admissions system work', 'China\'s university admission system is mainly based on the gaokao (Higher Education Entrance Examination). The gaokao is a national standardized test organized by the Ministry of Education and conducted nationwide. Students\' scores in the college entrance examination are regarded as an important basis for university admission. Admission criteria generally include college entrance examination results and students\' comprehensive quality evaluation, such as interviews, sports results, artistic specialties, etc. Different universities and different majors have certain differences in the admission criteria.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (55, 'Education', 'admission criteria', 'China\'s university admission system is mainly based on the gaokao (Higher Education Entrance Examination). The gaokao is a national standardized test organized by the Ministry of Education and conducted nationwide. Students\' scores in the college entrance examination are regarded as an important basis for university admission. Admission criteria generally include college entrance examination results and students\' comprehensive quality evaluation, such as interviews, sports results, artistic specialties, etc. Different universities and different majors have certain differences in the admission criteria.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (56, 'Education', 'preferential policies', 'In China, there are preferential policies to encourage certain groups of students to gain university admission. For example, rural students and ethnic minority students can enjoy a certain bonus point policy to make up for their lack of educational resources and conditions. At the same time, the government also offers several scholarships and funding schemes to help students with financial difficulties gain access to higher education opportunities.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (57, 'Education', 'extracurricular activities and social services', 'China\'s education system encourages students to participate in extracurricular activities and social services. Schools usually provide a variety of extracurricular activities and club organizations, such as student clubs, scientific and technological innovation teams, art teams, etc., to meet students\' interests and development needs. In addition, some schools encourage students to participate in social service and volunteer activities to cultivate students\' sense of social responsibility and citizenship.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (58, 'Education', 'teacher training and recruitment work', 'In China, the training and recruitment of teachers is usually the responsibility of education administrations at all levels. Teacher training includes training in pedagogical theories and teaching skills, as well as the accumulation of internships and practical experience. Teachers are usually recruited through open competition or examinations, which are evaluated based on factors such as candidates\' academic qualifications, teaching experience, and professional competence.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (59, 'Education', 'salaries and professional development of teachers', 'There are certain differences in the remuneration and professional development of teachers in China\'s education system. In general, public-school teachers are better paid and welfare, while private school teachers may be treated relatively low. Teachers\' professional development is often related to their teaching ability, academic background, and educational experience. In terms of teacher professional development, China\'s education system encourages teachers to participate in continuing training, research, and professional development, and provides opportunities for promotion and title evaluation.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (60, 'Education', 'educational disparities', 'China\'s education system suffers from an imbalance in urban and rural education resources. Urban areas are relatively rich in educational resources, including high-quality schools, educational facilities, and educational opportunities. However, educational resources in rural areas are relatively insufficient, and there are problems such as insufficient teachers and backward educational facilities. The Government is working to address these issues by promoting a balance of educational resources by increasing the recruitment of rural teachers, improving educational facilities, and providing educational resource support.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (61, 'Education', 'nurturing students\' creativity and critical thinking', 'China\'s education system focuses on nurturing students\' creativity and critical thinking. During educational reform, more and more emphasis has been placed on cultivating students\' innovative ability and critical thinking, rather than just focusing on the transmission of knowledge and the cultivation of test-taking ability. The education department encourages teachers to adopt diversified teaching methods and evaluation methods, encourages students to think independently, ask questions and solve problems, and cultivates students\' creative thinking and innovative spirit.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (62, 'Education', 'academic burden of Chinese students', 'Chinese students have a relatively heavy academic load, and they usually study longer hours each day. Due to the highly competitive education and the cultural background that values test scores, students are required to attend various training courses and cram classes while completing school assignments to improve their competitiveness in examinations. As a result, students may study longer than normal class hours.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (63, 'Education', 'over-test-taking education', 'There is a problem of over-examination-oriented education in China\'s education system. Due to the importance of the college entrance examination for students\' future education and employment, many students and parents focus on test-taking skills and test scores, while neglecting to cultivate students\' comprehensive quality and creativity. This education model may lead to excessive learning and excessive competition among students, which will bring greater pressure to students.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (64, 'Education', 'reports of pressure and competition', 'Media and research institutions regularly report on pressure and competition in China\'s education system. Many students and parents have high expectations for education, believing that an individual\'s destiny can be changed through a good education. As a result, they pay a lot of attention to academic performance and progression opportunities, which increases stress and competition for students. At the same time, educational institutions and families will also provide students with various tutoring and training to improve their competitiveness.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (65, 'Education', 'expectations of students and parents', 'It is important to note that educational pressures and parental expectations do not apply to all students and families, and there may be differences between individuals. In addition, China\'s education system is also working hard to reduce students\' academic burden and improve the quality of education and promote the development of quality education and comprehensive evaluation.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (66, 'Education', 'opportunities to connect with foreign education systems', 'In China\'s education system, there are real opportunities to connect with foreign education systems. There are some international schools in China, which usually offer international courses that focus on foreign language teaching, such as the International Baccalaureate (IB), Cambridge International Curriculum, etc. These schools primarily serve expatriates and students from Chinese families interested in pursuing an international education. In addition, some Chinese public schools may also offer international curricula or educational cooperation programs with foreign schools.', 0, '2023-07-29 00:30:05', '2023-07-29 00:30:05');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (67, 'Education', 'moral education', 'In the Chinese education system, moral education and the cultivation of values are a very important part. The Chinese education system focuses on cultivating students\' sense of social responsibility, citizenship, and moral character. Education in these areas is mainly carried out through integrated curricula, moral education courses and cultural activities on campus. Schools usually offer some specific courses, such as ideological character, civic morality, and legal system, etc., to educate students on correct moral concepts and civic responsibility. In addition, the school organizes various social practices and volunteer activities for students to participate in social services and cultivate their moral literacy and civic awareness through hands-on experience.', 0, '2023-07-29 00:30:06', '2023-07-29 00:30:06');
INSERT INTO `chatgpt_clone`.`m_answer` (`id`, `field`, `keyword`, `answer`, `is_deleted`, `created_at`, `updated_at`) VALUES (68, 'Education', 'ethics and civic responsibility', 'In the Chinese education system, moral education and the cultivation of values are a very important part. The Chinese education system focuses on cultivating students\' sense of social responsibility, citizenship, and moral character. Education in these areas is mainly carried out through integrated curricula, moral education courses and cultural activities on campus. Schools usually offer some specific courses, such as ideological character, civic morality, and legal system, etc., to educate students on correct moral concepts and civic responsibility. In addition, the school organizes various social practices and volunteer activities for students to participate in social services and cultivate their moral literacy and civic awareness through hands-on experience.', 0, '2023-07-29 00:30:06', '2023-07-29 00:30:06');
